# ASP.NET Core (.NET Framework)
# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- azure-pipelines

pool: myLocalPool
# vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
- task: NuGetToolInstaller@1

- task: NuGetCommand@2
  inputs:
    restoreSolution: '$(solution)'

- task: DotNetCoreCLI@2
  inputs:
    command: 'test'
    projects: ' Diploma.csproj'

- task: PublishAllureReport@1
  condition: always()
  displayName: Publish Report
  inputs:
    allureVersion: 2.27.0
    testResultsDir: .\bin\Debug\net8.0\allure-report\

- task: PublishPipelineArtifact@1
  condition: always()
  displayName: Publish Artifact
  inputs:
    targetPath: '$(Build.SourcesDirectory)\bin\Debug\net8.0\allure-report'
    publishLocation: 'pipeline'
